In [1]:
import numpy as np
import matplotlib.pyplot as plt
#from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split

In [2]:
data = np.load('./datasets/mnist_train_small.npy')
# data = tf.keras.datasets.mnist.load_data(path="mnist.npz")

In [3]:
data

array([[5, 0, 0, ..., 0, 0, 0],
       [7, 0, 0, ..., 0, 0, 0],
       [9, 0, 0, ..., 0, 0, 0],
       ...,
       [2, 0, 0, ..., 0, 0, 0],
       [9, 0, 0, ..., 0, 0, 0],
       [5, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [4]:
X = data[:, 1:]
y = data[:, 0]
# (X_train, y_train) , (X_test, y_test) = keras.datasets.mnist.load_data()

In [5]:
# X_train.shape, y_train.shape

In [6]:
# X_test.shape, y_test.shape

In [7]:
# plt.imshow(X_train[0].reshape(28, 28), cmap='gray')

In [8]:
# y_train[0]

In [9]:
 #X, y = make_blobs(n_samples=1000, centers=3, random_state=42)

In [10]:
#plt.scatter(X[:, 0], X[:, 1:], c = y)

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)


In [12]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((13399, 784), (13399,), (6600, 784), (6600,))

In [13]:
# scale this training and test datasets
# X_train = X_train / 255
# X_test = X_test / 255

In [14]:
# convert the 2-d matrix to a 1-d array by using this
# X_train = X_train.reshape(-1,28,28,1)    #training set
# X_test = X_test.reshape(-1,28,28,1)      #test set

In [15]:
# from sklearn.neighbors import KNeighborsClassifier

In [16]:
# model = KNeighborsClassifier()

In [17]:
#training the model happens in fit function
# plotting the points on the graph happens
#no work is happening in teh training the knn modebl 
# model.fit(X_train, y_train)

In [18]:
# model.predict(X_test[:10])

In [19]:
# y_test[:10]

In [20]:
# plt.imshow(X_test[8].reshape(28, 28), cmap='gray')

In [21]:
# model.score(X_test[:100], y_test[:100])

In [22]:
# plt.imshow(X_test[24].reshape(28, 28), cmap='gray')

In [23]:
# y_test[24]

***CUSTOM KNN***

In [28]:
class CustomKNN:
    #constructor
    def __init__(self, n_neighbours=5):
        self.n_neighbours = n_neighbours
        
    #training functions
    def fit(self, X, y):
        # training points
        self._X = X.astype(np.int64)
        self._y = y.astype(np.int64)
    
    #predict point
    #given a single point tell mew which class it belongs to
    def predict_point(self, point):
        #store the distances of given points from each point in the training data
        list_dist=[]
        
        #points from training data
        for x_point, y_point in zip(self._X, self._y):
            dist_point = ((point - x_point) ** 2).sum()
            list_dist.append([dist_point, y_point])
            
        #sorting the list according to the distance
        sorted_dist = sorted(list_dist)
        top_k = sorted_dist[:self.n_neighbours]
        
        #taking the count
        items, count = np.unique(np.array(top_k)[:, 1], return_counts=True)
        ans = items[np.argmax(count)]
        return ans
    
    #predict
    #give me answer foe each number in the array
    def predict(self, X):
        results = []
        
        for point in X:
            results.append(self.predict_point(point))
            
        return np.array(results, dtype=int)
    
    #score to measure accuracy
    def score(self, X, y):
        return sum(self.predict(X) == y) / len(y)

In [29]:
model2 = CustomKNN()

In [30]:
model2.fit(X_train, y_train)

In [31]:
model2.predict(X_test[:10])

array([1, 7, 0, 9, 4, 5, 4, 6, 9, 2])

In [32]:
y_test[:10]

array([7, 7, 0, 9, 4, 5, 4, 6, 9, 2], dtype=uint8)

In [33]:
model2.score(X_test[:100], y_test[:100])

0.95

## DEMO

In [ ]:
#what zip does
X = [1, 2, 3, 2, 4]
y = [0, 1, 2,1 , 0]
list(zip(X, y))

In [ ]:
#to count the most occurrence
li = [
    [2, 0],
    [4, 1],
    [5, 0],
    [7, 0],
    [11, 2]
]

In [ ]:
sorted_li = sorted(li)

In [ ]:
top_k = sorted_li[:5]

In [ ]:
top_k

In [ ]:
li, counts = np.unique(np.array(top_k)[:, 1], return_counts=True)

In [ ]:
np.argmax(counts)